package com.ecommerce.service;
import com.ecommerce.dto.ApiDtos.*; import com.ecommerce.entity.*; import com.ecommerce.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service
public class OrderService {
 private final OrderRepository orders; private final OrderItemRepository items; private final UserService users; private final CartService carts; public OrderService(OrderRepository o,OrderItemRepository i,UserService u,CartService c){orders=o;items=i;users=u;carts=c;}
 @Transactional public OrderResponse place(String name,CheckoutRequest r){User u=users.find(name);List<CartItem> cart=carts.raw(u);if(cart.isEmpty())throw new IllegalArgumentException("Cart is empty");CustomerOrder o=new CustomerOrder();o.setCustomer(u);o.setAddress(r.address());o.setCity(r.city());o.setCountry(r.country());o.setPostalCode(r.postalCode());o.setPhone(r.phone());double total=0;for(CartItem c:cart){Product p=c.getProduct();OrderItem x=new OrderItem();x.setOrder(o);x.setProductId(p.getId());x.setSellerId(p.getSeller().getId());x.setSellerUsername(p.getSeller().getUsername());x.setCustomerUsername(u.getUsername());x.setOrderedAt(o.getCreatedAt());x.setProductName(p.getBrand()+" "+p.getModel());x.setImageUrl(p.getImageUrl());x.setPrice(p.getPrice());x.setQuantity(c.getQuantity());o.getItems().add(x);total+=p.getPrice()*c.getQuantity();}o.setTotal(total);CustomerOrder saved=orders.save(o);carts.clear(u);return response(saved);}
 @Transactional(readOnly=true) public List<OrderResponse> mine(String n){return orders.findByCustomerOrderByCreatedAtDesc(users.find(n)).stream().map(this::response).toList();}
 public List<SaleResponse> sales(String n){User seller=users.find(n);return items.findBySellerIdOrderByIdDesc(seller.getId()).stream().map(i->new SaleResponse(i.getId(),i.getProductName(),i.getImageUrl(),i.getPrice(),i.getQuantity(),i.getCustomerUsername(),i.getOrderedAt())).toList();}
 private OrderResponse response(CustomerOrder o){List<OrderItemResponse> lines=o.getItems().stream().map(i->new OrderItemResponse(i.getId(),i.getProductId(),i.getProductName(),i.getImageUrl(),i.getPrice(),i.getQuantity(),i.getSellerUsername())).toList();return new OrderResponse(o.getId(),o.getAddress(),o.getCity(),o.getCountry(),o.getPostalCode(),o.getPhone(),o.getTotal(),o.getCreatedAt(),lines);}
}
